### ISSUE TITLE
Older Plugin Versions

### ISSUE THREAD

**Issue by cyber-r** [ibm-datapower/datapower-configuration-manager#10]
Hi 

Is there anyway i can get older stable version of this plugin ? i.e version#6.

**Comment by richgroot** [comment]
I'm working on the original problem today/tomorrow.

**Comment by cyber-r** [comment]
Thank you. 
Yes, if original issue https://github.com/ibm-datapower/datapower-configuration-manager/issues/6
can be fixed, no need of prev. version.

**Comment by richgroot** [comment]
The two latest commits resolve this problem for both command line and for the UCD plugin.
