### ISSUE TITLE
Flush stylesheet cache and document cache

### ISSUE THREAD

**Issue by andyK544** [ibm-datapower/datapower-configuration-manager#15]
Hello,

I've started exploring the DCM tool and it is great. 

Does it support Flush Stylesheet cache and Document cache yet? I did not see any targets defined for them in the "deploy.ant.xml".

I believe it is imperative to flush a stylesheet cache or document cache after using "upload-from-def" for xslt or any lookup documents.

Thanks

**Comment by nhmathis** [comment]
Hi,

Searching deep within the project, I've found test wdp calls for flushing the stylesheet and document caches. One should be able to fairly easily shift these commands in the `deploy.ant.xml` and make them fully supported. 

FlushStylesheetcache: https://github.com/ibm-datapower/datapower-configuration-manager/blob/2a2a2b81e455afd1768f5ee6b0464ecd58dd6f6b/tests-wdp/cache-operations.ant.xml#L144
FlushDocumentcache: https://github.com/ibm-datapower/datapower-configuration-manager/blob/2a2a2b81e455afd1768f5ee6b0464ecd58dd6f6b/tests-wdp/cache-operations.ant.xml#L90
