### ISSUE TITLE
Direct SOMA call feature request

### ISSUE THREAD

**Issue by samdjones** [ibm-datapower/datapower-configuration-manager#18]
Hello,

Would it be possible to add a feature to make SOMA calls somewhat directly? It would simply take an in input request file, post it to the SOMA interface and write the response to an output file.

Why you may ask? There are often times when we need to do something and there is not an existing DCM feaure, or an existing DCM features doesn't quite do things as we need, and there is no time to wait for new DCM features/enhancements. The standard Ant tasks are inadequate so in the past I've used the Google Missing Link Ant library or Curl to make direct SOMA calls. But many customers won't allow us to install them, so I would like to see a DCM feature added to do it.

Hopefully this isn't a difficult feature to add since the existing tasks obviously make use of SOMA calls already - the underlying API just needs opening up a little to the public. I'm happy to attempt the change myself and submit a pull request if I'm pointed in the right direction..

Cheers,
Sam

**Comment by socrates58** [comment]
Sam,
Would a python script that does SOMA be a fit for your needs? I've got some scripts lying around that do direct SOMA calls.

**Comment by samdjones** [comment]
Thanks but we can't install anything else - it has to be Ant+DCM only

**Comment by samdjones** [comment]
I went ahead and added the feature to DCM - see my latest pull request https://github.com/ibm-datapower/datapower-configuration-manager/pull/23

It's pretty straightforward and takes two parameters:
    
    soma.request - This is the raw SOMA request input filename
    soma.request - This is the raw SOMA response output filename

**Comment by richgroot** [comment]
Thanks for the contribution, Sam!  Nicely done!
