### ISSUE TITLE
Changes to the interior layers

### ISSUE THREAD

**Issue by samdjones** [ibm-datapower/datapower-configuration-manager#19]
Hello,

I was planning to add some new features to DCM, however I saw this on the Wiki home page:

"Interior layers include XSLT and Java. You are discouraged from using these interior layers directly as a long-term project is underway to replace much of this code."

Can you please disclose how things are going to change? Until this is cleared up I fear any new features I add will be rendered obsolete when the design changes are made.

NB: in my opinion the mix of Ant, XSLT and tightly coupled Java makes things overly complicated. I would instead rather see the heavy lifting done entirely in XSLT, with the Java code acting as little more than a thin proxy to the SOMA web service interface. This way most DataPower developers would more easily be able to contribute and customise DCM, since they should already have XSLT skills to work with DataPower. This is just my initial opinion, happy to discuss in detail if you like :-)

Cheers,
Sam

**Comment by samdjones** [comment]
*Bump*

Can we have a status update please? I'm willing to add several new features provided they don't immediately become obsolete due to structural DCM design changes..

Thanks,
Sam

**Comment by richgroot** [comment]
Sam,
I began a serious rework of the internals of DCM and then shelved it.  I doubt that I'll pick it up again any time soon.
Thanks,
Rich
