### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by iLoveTux** [ibm-datapower/datapower-configuration-manager#2]
I am running this on a Lubuntu 14.10 workstation. 

I cloned the repository, I installed the pre-requisites and I built the project as per your instructions in README.md. Everything went as expected.

Now I am looking through the resulting directory structure, and there is no documentation...

I am what I would consider a competent sytem admin/developer, but I need some sort of pointer as to where to go now...

Could you please add a file which would give some basic commands I would issue, from there I am sure I can dig in and discover the more advanced functionality, but without a starting point I find I am unable to do a thing.

**Comment by richgroot** [comment]
That new documentation is now available in the wiki.  Check out the [Quick Start](https://github.com/ibm-datapower/datapower-configuration-manager/wiki/Quick-Start) page for getting DCM installed and the [Easy On Ramp](https://github.com/ibm-datapower/datapower-configuration-manager/wiki/Easy-On-Ramp) page for getting started with the basic concepts and a decent way  of organizing your DCM assets.
