### ISSUE TITLE
Missing file: mbaas-downloadFilestore.xsl in dcm-taskdefs.ant.xml?

### ISSUE THREAD

**Issue by wenism** [ibm-datapower/datapower-configuration-manager#22]
Hello everyone,

I am trying out an ant task that downloads the filestore by using the downloadFilestore macrodef in datapower-configuration-manager/dcm/src/dcm-taskdefs.ant.xml but it is failing because this macrodef cannot find mbaas-downloadFilestore.xsl  (line 683 of revision 3e25998, April 14 2016):
`<nxslt inprop="rawxml" outprop="tmp" xsl="mbaas-downloadFilestore.xsl"/>`

If you have this file, please commit into the repository? 

Thank you.

**Comment by wenism** [comment]
I was told that Richard has the file and he intends to upload/merge it. That's encouraging. Will wait for the file before closing this issue.

**Comment by wenism** [comment]
Hello everyone,
What's the status of the said file? 
sincerely, Wen.

**Comment by richgroot** [comment]
My apologies, the downloadFilestore macrodef jumped the fence from the copy of DCM that I use for my day job and got into the public DCM pasture.  I've completed downloadFilestore and it should be ready for public consumption.  Thanks for your patience!

**Comment by wenism** [comment]
Thanks Rich.
