### ISSUE TITLE
conflicts not resolved during latest merge?

### ISSUE THREAD

**Issue by samdjones** [ibm-datapower/datapower-configuration-manager#24]
It appears the last merge went wrong. See build.xml for example - it is now invalid xml

**Comment by richgroot** [comment]
Thanks Sam, looking into it now.

**Comment by samdjones** [comment]
I'm pretty sure the merge conflict was with my previous change which mostly just fixed the Ant download. The more recent change also appears to resolve the same issue so you can simply accept the latter version of build.xml in it's entirely without losing anything.

**Comment by richgroot** [comment]
Thanks, Sam, the merge conflict was from the reorg submitted by the UCD team and I just whiffed the ball.  Should be corrected now, along with your pull request having been merged.
