### ISSUE TITLE
Export/Import multiple WSPs and MPGW - Functionality yet.??

### ISSUE THREAD

**Issue by vinchauhan** [ibm-datapower/datapower-configuration-manager#25]

**Comment by samdjones** [comment]
Just this week I made a kinda hacky DCM export feature because I needed one in a hurry. It takes as input an XML file listing the required export objects, optionally including referenced objects and files. In other words just like the GUI export function. Happy to tidy it up and share but it might be a week or two before I find the time.

**Comment by samdjones** [comment]
Oh wait the features was apparently just added in the latest merge so when the build is fixed you should be good to go :-)

**Comment by vinchauhan** [comment]
I did customized one for me too by creating service names as a comma
separated list and the calling the export-service task looping using
groovy. Since DCM doesn't not have any contrib in it. I preferred to loop
through using groovy.

Thanks,
Vineet

**Comment by richgroot** [comment]
Yes, please!

**Comment by samdjones** [comment]
Ah I see now - the new (to me at least) export feature only exports a single object, not multiple objects as my hack does. OK I'll look merging the two appoaches.

**Comment by gitUser2k17** [comment]
Hi Sam,

I have similar requirement to upload multiple services. Can you please share the files you modified and a sample command?

Thanks.

**Comment by samdjones** [comment]
Hello,

I now have it on my list to contribute the feature to DCM hopefully by the end of this week hopefully (next week latest). Sorry I can't share sooner - better done properly.

Cheers.

**Comment by samdjones** [comment]
Done: https://github.com/ibm-datapower/datapower-configuration-manager/pull/39

**Comment by gitUser2k17** [comment]
Thank you So much Sam. I will take a look at this.
