### ISSUE TITLE
IBM UCD - using datapower plugin for deployment - timeout issue

### ISSUE THREAD

**Issue by Asim80** [ibm-datapower/datapower-configuration-manager#33]
Hi There,
I am using the datapower plugin to do deployment to datapower. The deployment actually works however the status on UCD ends in failure due to the timeout issue. Please find the attached screen from UCD. Logs attached as well. Tks

[DP-logs-for-UCD.txt](https://github.com/ibm-datapower/datapower-configuration-manager/files/553882/DP-logs-for-UCD.txt)
![ucd_deployment_status](https://cloud.githubusercontent.com/assets/23081143/19735215/aa3dea90-9b78-11e6-9637-b9ae2687272d.png)
[UCD_Error_Logs.txt](https://github.com/ibm-datapower/datapower-configuration-manager/files/553883/UCD_Error_Logs.txt)
[UCD_stdOut_logs.txt](https://github.com/ibm-datapower/datapower-configuration-manager/files/553884/UCD_stdOut_logs.txt)

**Comment by richgroot** [comment]
I scanned through UCD_stdOut_logs.txt for

status="ERROR"

There are several certificates that did not import correctly because of
some problem with one or more password aliases.  Set up those password
alias entries and give it another try.

As a general debugging tip when Import is failing, it is often useful to do
the import through the web browser since it does a better job of showing
the errors.

Hope this helps.

Thanks,
Rich

**Comment by Asim80** [comment]
Set up those password alias entries and give it another try. 
**- where to set these password? The passwords do exist in the environment from where the export of the package was taken, in firmware 7 the passwords doesn't get imported.**

**Comment by richgroot** [comment]
Yeah, password aliases cannot be (iirc) exported, which is a key part of
their contribution to the security of the appliance.  You'll want to
manually create new password aliases on the target appliance before the
import can be expected to complete successfully.

**Comment by RahulRdec** [comment]
Hi Rich,

Is there any way we can create this Password Alias Object at run time. May be using DCM  (object-from-def) or any other option?

**Comment by Asim80** [comment]
Getting a success flag in UCD now. Created password alias in dp first then followed by the ucd deployment. Thanks
