### ISSUE TITLE
download-files target file error

### ISSUE THREAD

**Issue by zfivgas** [ibm-datapower/datapower-configuration-manager#34]
I am trying to use the download-files task to download a target file, however, I am getting the following error:

*Removed*\datapower-configuration-manager-master\deploy.ant.xml:609: The following error occurred while executing this line:
*Removed*\datapower-configuration-manager-master\src\dcm-taskdefs.ant.xml:739: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.

I am just trying to do something basic like pull a file named inputs.xml from temporary:  I am using these two parameter inputs, however, for filename I've tried different variations.

-Dfilestore=temporary:
-Dfiles=inputs.xml

I am able to download the complete filestore successfully if I leave out the files parameter.  I assume it has something to do with my syntax but I can't say for sure.

**Comment by wenism** [comment]
zfivgas, the files argument should be in xml format e.g.:
`<downloadFiles><file>/folderA/fileA.xml</file></downloadFiles>`
It is a bit clunky but, in order to upload nested files correctly, the step needs to create the relevant folders in the filestore. The markup provides both the full path and the file.

**Comment by zfivgas** [comment]
Thank you.  I am able to get it to work now.

**Comment by ChubeZiobe** [comment]
plugin: DataPower, id: com.ibm.datapower, version: 12  
files=<downloadFiles><file>/folderA/fileA.xml</file></downloadFiles>
filestore=local:

@zfivgas, I got this error: < was unexpected at this time.
@wenism, how did you get your to work?

Thanks

**Comment by ChubeZiobe** [comment]
sorry... it stripped out the xml tags.. the files argument is actually in xml tag like you recommended.

**Comment by poornapeethani** [comment]
Hi All,
I am trying to download files from temporary:///securebackup/ from file management i am getting 500 response error- ant -f deploy.ant.xml  -Ddevice=device  -Duid=123345 -Dpwd=test                      -Ddomain=default -Dfilestore=temporary:///securebackup/  -Ddownload-dir.to=F:\DataPower\DCM-DatapowerConfigurationManager\  download-files      
Can someone help me plz...……………...
