### ISSUE TITLE
How to recursively deploy directories in DataPower using dcm plugin under UrbanCode

### ISSUE THREAD

**Issue by rohgoyal** [ibm-datapower/datapower-configuration-manager#35]
I am using DCM plugin version 8 with UrbanCode deploy.
My requirements is to copy a folder which has files and other sub-directories which then has more files and sub-directories to DataPower.

`<dcm:upload local="${deploy.dir}/Mapping/**.*" remotedir="${mapping.dir}"/>`
If I use the above statement in my dcm-upload definition, it only deploys the files and immediate folders under the Mapping folder to the DataPower destination folder. So if the Mapping folder has a folder 'xyz' under it, the contents of the folder 'xyz' do not get copied. i.e. no recursion.

The behaviour doesn't change with this statement
`<dcm:upload localdir="${deploy.dir}/Mapping" match="**.*" remotedir="${mapping.dir}"/>`
Can someone suggest a way to recursively deploy/upload files and sub-directories recursively to DataPower using DCM plugin using UrbanCode?

**Comment by dorser** [comment]
I was able to achieve that using:
`<dcm:upload local="basedir/**" remotedir="local:///"/>`

I was also able to create my own target using alternative example from the wiki:
[https://github.com/ibm-datapower/datapower-configuration-manager/wiki/dcm:upload-element](https://github.com/ibm-datapower/datapower-configuration-manager/wiki/dcm:upload-element)
