### ISSUE TITLE
Updating Specific xslt or xml file in datapower

### ISSUE THREAD

**Issue by sk9025** [ibm-datapower/datapower-configuration-manager#46]
Hi,

I wanted to update a particular xslt/xml file from easy start project. 
Will it possible ? .If possible could you please guide me how to do  and where to start ?

When running this project it is dependent of DCM jar file.Can we run the easystart project without using the DCM jar ?

Can you please tell me the answer for this.

Thanks
SK

**Comment by nhmathis** [comment]
Hi @sk9025,

If you haven't already seen it, the [Quick Start] (https://github.com/ibm-datapower/datapower-configuration-manager/wiki/Quick-Start) and [Easy On Ramp](https://github.com/ibm-datapower/datapower-configuration-manager/wiki/Easy-On-Ramp) Wiki guides are a great place to start. This will guide you through your first deployment using the the DCM. 

More specifically, are you looking to update the contents of the xslt/xml file or simply overwrite it with a new version? If the later, you'll want to look close at the Import Phase 2 section. This project enables to import/deployment of new files and folders to a Datapower instance. You'll need to export a zip file from Datapower and run the [import-from-def] (https://github.com/ibm-datapower/datapower-configuration-manager/wiki/Ant-targets-for-deploy.ant.xml#import-from-def-was-import-changed) command without specifying a definition file. More can be found on the definition file in the Wiki.

This repository contains two separate projects: Datapower Configuration Manager (DCM) and the Datapower plugin for IBM UrbanCode Deploy. The plugin utilizes the DCM to run commands against the Datapower server. For this reason, the dcm.jar is required for all projects and walkthroughs in this repository. The Wiki tutorials describe various methods of using the DCM tool. The plugin provides many steps that simply call these same commands. If you wish to run plugin steps, it's strongly encouraged that you learn how to interact with the DCM tool.

**Comment by sk9025** [comment]
Hi  nhmathis,

First of all thanks for the quick reply.I will go through the wiki and all stuff.

thanks once again for clarifying my doubts.

**Comment by richgroot** [comment]
You should be able to use the "upload-from-def" target, with a definition
file that includes this, as an example:

<dcm:upload local="${user.dir}/dev/bob.xml"
remotedir="local:///someservice"/>

This will upload ~/dev/bob.xml to local:///someservice/bob.xml, overwriting
local;///someservice/bob.xml if it already exists.

Hope this helps,
Rich
