### ISSUE TITLE
Export Object Error

### ISSUE THREAD

**Issue by bmarur** [ibm-datapower/datapower-configuration-manager#59]
Hello Experts,

I was evaluating the DCM component, I ran in to below error while executing Export-Object method, 

`C:\Users\<user>\Documents\dcm\dcm\deploy.ant.xml:658: The following error occurred while executing this line:
C:\Users\<user>\Documents\dcm\dcm\src\dcm-taskdefs.ant.xml:136: Failed to export object castIron_LogServer_POC of class=MultiProtocolGateway from domain Test_Bharath on nc-wec-esbgw-a0r.<company>.com.`

It looks like the Soma request is executing correctly and I was able to see the Succusful Soma response in the capture file, however, the command seems to error out while exporting intended objects, I have included the DCM command & Soma Capture file for your reference.

```
**Command**
ant -f deploy.ant.xml -Ddcm.dir=. -Dhost=nc-wec-esbgw-a0r.wellsfargo.com -Duid=xgidbrt -Dpwd=xxxxx -Ddomain=Test_Bharath -Dobject.class=MultiProtocolGateway -Dobject.name=castIron_LogServer_POC -Dexport.file="C:/Users/<user>/Documents/dcm/ant_tutorials/exports" -Dcapturesoma="C:/Users/<user>/Documents/dcm/ant_tutorials/capture_soma"  export-object
```

Please let me know, where do I seem to go wrong 

[capture_soma.txt](https://github.com/ibm-datapower/datapower-configuration-manager/files/1085344/capture_soma.txt)

Thanks,
Bharath

**Comment by dorser** [comment]
Try adding the following parameter: -Dall.files=false
Let me know if that works for you...
Gonna fix this now..

**Comment by dorser** [comment]
Yup, I didn't add a default value.
I'll push this now.

**Comment by bmarur** [comment]
@dorser,

Thanks for the response and I have made this change in "deploy.ant.xml" 

 **<property name="all.files" value="false"/>**

however, I still seem to have issues executing this export-object method, Please find the error snippet below, 

`Buildfile: C:\Users\<user>\Documents\dcm\dcm\deploy.ant.xml

clean:
   [delete] Deleting directory C:\Users\<user>\Documents\dcm\dcm\tmp

-init-dir:
    [mkdir] Created dir: C:\Users\<user>\Documents\dcm\dcm\tmp

-check-std-args:

check-access:

export-object:
     [echo] Raw response for export: ${export_response}

BUILD FAILED
C:\Users\<user>\Documents\dcm\dcm\deploy.ant.xml:659: The following error occurred while executing this line:
C:\Users\<user>\Documents\dcm\dcm\src\dcm-taskdefs.ant.xml:136: Failed to export object castIron_LogServer_POC of class=MultiProtocolGateway from domain Test_Bharath on nc-wec-esbgw-a0r.<company>.com.

Total time: 3 seconds
`

I have looked at the capture soma file to check If there are any errors in the Soma XML, I don't any issues with the request payload, Now, I see the all-files=false attribute appearing in the SOMA request and there is SOMA response as well Base-64 encoded package embedded in the Soap tags. I have incorporated the DCM command and Soma Capture file for your reference.

**Command**
ant -f deploy.ant.xml -Ddcm.dir=. -Dhost=nc-wec-esbgw-a0r.<company>.com -Duid=xxxxxx -Dpwd=xxxxx -Ddomain=Test_Bharath -Dobject.class=MultiProtocolGateway -Dobject.name=castIron_LogServer_POC -Dexport.file="C:/Users/<user>/Documents/dcm/ant_tutorials/exports" -Dcapturesoma="C:/Users/<user>/Documents/dcm/ant_tutorials/capture_soma" -Dall.files=false  export-object


[capture_soma.txt](https://github.com/ibm-datapower/datapower-configuration-manager/files/1088322/capture_soma.txt)

Please advise!

Thanks,
Bharath

**Comment by dorser** [comment]
@bmarur can you please run the ant with -v flag and copy its output?

**Comment by bmarur** [comment]
Hello @dorser 

Please find the command line output while I ran "ant -v" command.

I seem to get the same error when I run export-object method after executing this command.

Please let me know, If you need anything else, I'll be happy to get them to you!

Thanks for your help!

[ant_run.txt](https://github.com/ibm-datapower/datapower-configuration-manager/files/1088814/ant_run.txt)

Thanks,
Bharath

**Comment by dorser** [comment]
@bmarur sorry for not being clear on this.
I meant running the original command and add -v to it.

ant -f deploy.ant.xml -Ddcm.dir=. -Dhost=nc-wec-esbgw-a0r..com -Duid=xxxxxx -Dpwd=xxxxx -Ddomain=Test_Bharath -Dobject.class=MultiProtocolGateway -Dobject.name=castIron_LogServer_POC -Dexport.file="C:/Users//Documents/dcm/ant_tutorials/exports" -Dcapturesoma="C:/Users//Documents/dcm/ant_tutorials/capture_soma" -Dall.files=false **-v** export-object

**Comment by bmarur** [comment]
Hello @dorser,

Thanks for the quick response

yes, I have run it with -v flag in the command, Please find the console output, It looks like it has failed in the Java Code. I have attached Soma Capture and Console output for your reference.

Please let me know, If you need anything else, I'll be happy to get it to ya!

[capture_soma.txt](https://github.com/ibm-datapower/datapower-configuration-manager/files/1089112/capture_soma.txt)
[ant_run.txt](https://github.com/ibm-datapower/datapower-configuration-manager/files/1089114/ant_run.txt)


Thanks,
Bharath

**Comment by bmarur** [comment]
@dorser , any update on this issue ?

**Comment by dorser** [comment]
Hi,
Unfortunately, not yet.
I couldn't reproduce the problem...

When did you pull the repo for the last time?

**Comment by bmarur** [comment]
@dorser,

It was on Jun 20 at 12:20 PM EST, I have just downloaded a latest copy and ran the command again but, It doesn't seem to resolve, I'm having a feeling that it has something to do with the length of my command while I execute this in windows command line utility, what is your environment ? 

just so, I understand, is my command working for you ? I was wondering, I can match up to your environment and try it out there.

I guess the properties are parsing fine from the command, If you look at the below is the Log snippet

```
C:\Users\<user>\Documents\dcm\dcm\deploy.ant.xml:659: The following error occurred while executing this line:
C:\Users\<user>\Documents\dcm\dcm\src\dcm-taskdefs.ant.xml:136: Failed to export object castIron_LogServer_POC of class=MultiProtocolGateway from domain Test_Bharath on nc-wec-esbgw-a0r.<company>.com
```

In addition, should this property be set to "all.files=false" or "allfiles=false"

	`<property name="all.files" value="false"/>`

Again, here's my command

`ant -f deploy.ant.xml -Ddcm.dir=. -Dhost=nc-wec-esbgw-a0r.company.com -Duid=xxxxxx -Dpwd=xxxxx -Ddomain=Test_Bharath -Dobject.class=MultiProtocolGateway -Dobject.name=castIron_LogServer_POC -Dexport.file="C:/Users/user/Documents/dcm/ant_tutorials/exports" -Dcapturesoma="C:/Users/user/Documents/dcm/ant_tutorials/capture_soma" -Dall.files=false -v export-object`

I see that Soma request has also been executed successfully and I have shared the Capture Soma file, If you don't mind could you please compare my command and Soma Capture and see, If there is any difference ..

Please let me know, when you have an update..

Thanks,
Bharath

**Comment by dorser** [comment]
@bmarur 
Is should be `all.files`

I ran it on both Ubuntu 16.04 and Windows 10.
JDK8_131 and both ant 1.9.7 and 1.10.1.

Here is the output from Windows using the exact command:

```
ant -f deploy.ant.xml -Ddcm.dir=. -Dhost=nc-wec-esbgw-a0r.company.com -Duid=admin -Dpwd=datapower -Ddomain=Test_Bharath -Dobject.class=MultiProtocolGateway -Dobject.name=castIron_LogServer_POC -Dexport.file="C:/Users/dor/Documents/dcm/ant_tutorials/exports" -Dcapturesoma="C:/Users/dor/Documents/dcm/ant_tutorials/capture_soma" -Dall.files=false -v export-object
Apache Ant(TM) version 1.10.1 compiled on February 2 2017
Buildfile: C:\datapower-configuration-manager-master\datapower-configuration-manager-master\deploy.ant.xml
Detected Java version: 1.8 in: C:\Program Files\Java\jdk1.8.0_131\jre
Detected OS: Windows 10
parsing buildfile C:\datapower-configuration-manager-master\datapower-configuration-manager-master\deploy.ant.xml with URI = file:/C:/datapower-configuration-manager-master/datapower-configuration-manager-master/deploy.ant.xml
Project base dir set to: C:\datapower-configuration-manager-master\datapower-configuration-manager-master
parsing buildfile jar:file:/C:/apache-ant-1.10.1-bin/apache-ant-1.10.1/lib/ant.jar!/org/apache/tools/ant/antlib.xml with URI = jar:file:/C:/apache-ant-1.10.1-bin/apache-ant-1.10.1/lib/ant.jar!/org/apache/tools/ant/antlib.xml from a zip file
[available] Searching C:\datapower-configuration-manager-master\datapower-configuration-manager-master
[available] Found: dist\dcm.jar in C:\datapower-configuration-manager-master\datapower-configuration-manager-master
Override ignored for property "capturesoma"
parsing buildfile jar:file:/C:/datapower-configuration-manager-master/datapower-configuration-manager-master/dist/dcm.jar!/com/ibm/antlib.xml with URI = jar:file:/C:/datapower-configuration-manager-master/datapower-configuration-manager-master/dist/dcm.jar!/com/ibm/antlib.xml from a zip file
[antlib:ibm] Could not load definitions from resource ibm/antlib.xml. It could not be found.
Importing file C:\datapower-configuration-manager-master\datapower-configuration-manager-master\src\dcm-taskdefs.ant.xml from C:\datapower-configuration-manager-master\datapower-configuration-manager-master\deploy.ant.xml
Overriding previous definition of reference to ant.projectHelper
parsing buildfile C:\datapower-configuration-manager-master\datapower-configuration-manager-master\src\dcm-taskdefs.ant.xml with URI = file:/C:/datapower-configuration-manager-master/datapower-configuration-manager-master/src/dcm-taskdefs.ant.xml
 [macrodef] creating macro  backupDevice
 [macrodef] creating macro  exportObject
 [macrodef] creating macro  exportObjects
 [macrodef] creating macro  backupDomains
 [macrodef] creating macro  checkDeviceAccess
 [macrodef] creating macro  ensureDPSchema
 [macrodef] creating macro  createDomain
 [macrodef] creating macro  deleteDomain
 [macrodef] creating macro  disableObject
 [macrodef] creating macro  disableObjects
 [macrodef] creating macro  downloadFiles
 [macrodef] creating macro  downloadFilestore
 [macrodef] creating macro  enableObject
 [macrodef] creating macro  enableObjects
 [macrodef] creating macro  exportConfig
 [macrodef] creating macro  firmwareRollback
 [macrodef] creating macro  firmwareUpdate
 [macrodef] creating macro  getDomainStatus
 [macrodef] creating macro  getServiceStatus
 [macrodef] creating macro  idcredFromPKCS12
 [macrodef] creating macro  idcredFromKeyAndCert
 [macrodef] creating macro  importConfig
 [macrodef] creating macro  importConfigDPO
 [macrodef] creating macro  listFilestore
 [macrodef] creating macro  objectCreateByCopying
 [macrodef] creating macro  objectCreateByInline
 [macrodef] creating macro  objectCreateFromExport
 [macrodef] creating macro  objectDelete
 [macrodef] creating macro  objectModify
 [macrodef] creating macro  quiesceDomain
 [macrodef] creating macro  quiesceService
 [macrodef] creating macro  rawMgmtCall
 [macrodef] creating macro  removeCheckpoint
 [macrodef] creating macro  resetDomainConventionally
 [macrodef] creating macro  resetDomainDeleteCreate
 [macrodef] creating macro  restartDomain
 [macrodef] creating macro  restoreBackup
 [macrodef] creating macro  rewriteExport
 [macrodef] creating macro  rollbackCheckpoint
 [macrodef] creating macro  saveCheckpoint
 [macrodef] creating macro  saveDomainIfChanged
 [macrodef] creating macro  saveDomainIfChangedPrompt
 [macrodef] creating macro  saveDomainUnconditionally
 [macrodef] creating macro  secureBackup
 [macrodef] creating macro  setLogLevel
 [macrodef] creating macro  valcredFromFiles
 [macrodef] creating macro  unimportConfig
 [macrodef] creating macro  unquiesceDomain
 [macrodef] creating macro  unquiesceService
 [macrodef] creating macro  xalan
 [macrodef] creating macro  defprop
 [macrodef] creating macro  defprop-set
Overriding previous definition of reference to ant.projectHelper
Build sequence for target(s) `export-object' is [clean, -init-dir, -check-std-args, check-access, export-object]
Complete build sequence is [clean, -init-dir, -check-std-args, check-access, export-object, backup-device, import-from-def, import-changed, domain-delete, domain-create, save, domain-recreate, service-unquiesce, ltpa-password, idcred-from-key-and-cert, firmware-rollback, main, reboot, restore-backup, service-quiesce, download-files, host-alias-set, service-status, secure-backup-device, load-balancer-group-from-def, checkpoint-save, host-alias-remove, backup-domains, checkpoint-delete, set-log-level, objects-from-def, domain-init, checkpoint-restore, create-tam-files, debug, valcred-from-dir, import-dpo, certificate-from-def, domain-unquiesce, idcred-from-def, upload-from-def, key-from-def, domain-quiesce, idcred-from-p12, domain-reset, object-status, raw-mgmt-call, upload-dir, valcred-from-def, domain-restart, firmware-update, , export-objects]

clean:
   [delete] Deleting directory C:\datapower-configuration-manager-master\datapower-configuration-manager-master\tmp
   [delete] Deleting directory C:\datapower-configuration-manager-master\datapower-configuration-manager-master\tmp

-init-dir:
    [mkdir] Created dir: C:\datapower-configuration-manager-master\datapower-configuration-manager-master\tmp
    [mkdir] Skipping C:\datapower-configuration-manager-master\datapower-configuration-manager-master\schemas because it already exists.

-check-std-args:

check-access:

export-object:
Override ignored for property "all.files"
     [echo] Exported object castIron_LogServer_POC into C:/Users/dor/Documents/dcm/ant_tutorials/exports where
     [echo] class=MultiProtocolGateway ref-objects=true ref-files=true domain=Test_Bharath hostname=nc-wec-esbgw-a0r.company.com.

BUILD SUCCESSFUL
Total time: 15 seconds
```
SOMA output looks the same.

Still looking into the java...

**Comment by bmarur** [comment]
@dorser,

ha! your command has executed without a flaw!

I even tried to execute this on UNIX system, It has given me the same error

**command**:

` ant -f deploy.ant.xml -Ddcm.dir=. -Dhost=nc-wec-esbgw-a0r.company.com -Duid=xgidbrt -Dpwd=xxxxxx -Ddomain=Test_Bharath -Dobject.class=MultiProtocolGateway -Dobject.name=castIron_LogServer_POC -Dexport.file="/var/tmp/dcm/ant_tutorials/exports" -Dcapturesoma="/var/tmp/dcm/ant_tutorials/capture_soma" -Dall.files=false -v export-object`

**Error log**
`
clean:

-init-dir:
    [mkdir] Created dir: /var/tmp/dcm/dcm/tmp
    [mkdir] Skipping /var/tmp/dcm/dcm/schemas because it already exists.

-check-std-args:

check-access:

export-object:
Override ignored for property "all.files"
Property "export_success" has not been set
Property "export_response" has not been set
     [echo] Raw response for export: ${export_response}

BUILD FAILED
/var/tmp/dcm/dcm/deploy.ant.xml:659: The following error occurred while executin                                                                                                 g this line:
/var/tmp/dcm/dcm/src/dcm-taskdefs.ant.xml:136: Failed to export object castIron_                                                                                                 LogServer_POC of class=MultiProtocolGateway from domain Test_Bharath on nc-wec-e                                                                                                 sbgw-a0r.wellsfargo.com.
        at org.apache.tools.ant.taskdefs.Exit.execute(Exit.java:164)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                                 sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.jav                                                                                                 a:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
        at com.ibm.dcm.taskIf.execute(taskIf.java:68)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.                                                                                                 java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                                 sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.jav                                                                                                 a:106)
        at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                                 sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.jav                                                                                                 a:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                                 sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.jav                                                                                                 a:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.jav                                                                                                 a:402)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                                 sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.jav                                                                                                 a:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExe                                                                                                 cutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:857)
        at org.apache.tools.ant.Main.startAnt(Main.java:236)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)
`
I'm wondering, If you could execute it by referencing my DCM package, If that would reproduce the issue. I cannot attach it here due to the file size, Is there a code repo where I can upload my Source directory. 

Please let me know..


Thanks,
Bharath

**Comment by dorser** [comment]
You can create a repo on GitHub and push your code there.

Can you try running this command:
`ant -f deploy.ant.xml -Ddcm.dir=. -Dhost=nc-wec-esbgw-a0r.company.com -Duid=dor -Dpwd=datapower -Ddomain=Test_Bharath -Dobject.class=MultiProtocolGateway -Dobject.name=castIron_LogServer_POC -Dexport.file="C:/Users/dor/Documents/dcm/ant_tutorials/exports" -Dcapturesoma="C:/Users/dor/Documents/dcm/ant_tutorials/capture_soma" -Dall.files=false -Ddumpinput=true -Ddumpoutput=true -v export-object`

Hopefully this will give us more input on what's going on.

**Comment by bmarur** [comment]
Hello @dorser,

I was able to get the issue resolved, It was just that when I gave the export.file parameter in the ant command, I was actually referring to directory rather the actual file name, I was under impression that export.file is actually a directory by looking at the ANT target

`<target name="export-object" depends="-init-dir, check-access">

    <fail message="The Ant property 'domain' is required but not defined.  This is the name of a domain on the DataPower device." unless="domain"/>
    <fail message="The Ant property 'object.class' is required but not defined.  This is the object's class." unless="object.class"/>
    <fail message="The Ant property 'object.name' is required but not defined.  This is the name of the target object on the DataPower device." unless="object.name"/>
    <fail message="The Ant property 'export.file' is required but not defined.  This is the filename where the backup will be written." unless="export.file"/>

    <property name="ref.objects" value="true"/> 
    <property name="ref.files" value="true"/>
	<property name="all.files" value="false"/>

    <sequential>
      <local name="dirname"/>
      <dirname property="dirname" file="${export.file}"/>
      <if>
        <not>
          <isfileselected file="${dirname}">
            <writable/>
          </isfileselected>
        </not>
        <then>
          <fail message="No permission to write ${export.file} into folder ${dirname}"/>
        </then>
      </if>
    </sequential>

    <exportObject host="${host}" port="${port}" uid="${uid}" pwd="${pwd}" domain="${domain}" local="${export.file}"
      dumpinput="${dumpinput}" dumpoutput="${dumpoutput}" capturesoma="${capturesoma}"
      objclass="${object.class}" objname="${object.name}" refobjs="${ref.objects}" reffiles="${ref.files}" />

  </target>`  

The correct command is 

`ant -f deploy.ant.xml -Ddcm.dir=. -Dhost=nc-wec-esbgw-a0r.company.com -Duid=xxxxx -Dpwd=xxxxx -Ddomain=Test_Bharath -Dobject.class=MultiProtocolGateway -Dobject.name=castIron_LogServer_POC -Dexport.file="C:/Users/user/Documents/dcm/ant_tutorials/export/castIron_LogServer_POC.zip" -Dcapturesoma="C:/Users/user/Documents/dcm/ant_tutorials/capture_soma" -Dall.files=false -v export-object`

Thank you for sticking with me in troubleshooting this issue. Appreciate it!

If you have some time, Please look in to this issue as well, It has been a blocker for us to move forward

[](https://github.com/ibm-datapower/datapower-configuration-manager/issues/52) 

Thanks,
Bharath

**Comment by bmarur** [comment]
Hello @dorser,

I was able to get the issue resolved, It looks like export.file actually refers to the export file name rather than directory, I was misguided with the ANT target 

`<target name="export-object" depends="-init-dir, check-access">

    <fail message="The Ant property 'domain' is required but not defined.  This is the name of a domain on the DataPower device." unless="domain"/>
    <fail message="The Ant property 'object.class' is required but not defined.  This is the object's class." unless="object.class"/>
    <fail message="The Ant property 'object.name' is required but not defined.  This is the name of the target object on the DataPower device." unless="object.name"/>
    <fail message="The Ant property 'export.file' is required but not defined.  This is the filename where the backup will be written." unless="export.file"/>

    <property name="ref.objects" value="true"/> 
    <property name="ref.files" value="true"/>
	<property name="all.files" value="false"/>

    <sequential>
      <local name="dirname"/>
      <dirname property="dirname" file="${export.file}"/>
      <if>
        <not>
          <isfileselected file="${dirname}">
            <writable/>
          </isfileselected>
        </not>
        <then>
          <fail message="No permission to write ${export.file} into folder ${dirname}"/>
        </then>
      </if>
    </sequential>

    <exportObject host="${host}" port="${port}" uid="${uid}" pwd="${pwd}" domain="${domain}" local="${export.file}"
      dumpinput="${dumpinput}" dumpoutput="${dumpoutput}" capturesoma="${capturesoma}"
      objclass="${object.class}" objname="${object.name}" refobjs="${ref.objects}" reffiles="${ref.files}" />

  </target>`

Here's the command that I was able to successfully execute

`ant -f deploy.ant.xml -Ddcm.dir=. -Dhost=nc-wec-esbgw-a0r.wellsfargo.com -Duid=xgidbrt -Dpwd=xgi2D3V! -Ddomain=Test_Bharath -Dobject.class=MultiProtocolGateway -Dobject.name=castIron_LogServer_POC -Dexport.file="C:/Users/u583874/Documents/dcm/ant_tutorials/export/castIron_LogServer_POC.zip" -Dcapturesoma="C:/Users/u583874/Documents/dcm/ant_tutorials/capture_soma" -Dall.files=false -v export-object`

I guess, as I referenced the directory earlier, java code was trying to write a file with blank name and has thrown this access to file denied while I ran it in verbose.

Thank you for helping me out with this, Appreciate it!

If you have some time, I would appreciate, If you could please look in to this this issue.

[](https://github.com/ibm-datapower/datapower-configuration-manager/issues/52)

Thanks,
Bharath
