### ISSUE TITLE
NoClassDefFoundError: org/apache/xalan/processor/TransformerFactoryImpl 

### ISSUE THREAD

**Issue by abhip** [ibm-datapower/datapower-configuration-manager#6]
I have seen a customer getting the following error when using datapower plugin for IBM Urbancode Deploy

ucd/agent/var/plugins/com.ibm.datapower_8_39de24fa886abf9597a889b72d4c974c3ea004fe6a63aaf9622dd334533e527a/dcm/deploy.ant.xml:960: java.lang.NoClassDefFoundError: org/apache/xalan/processor/TransformerFactoryImpl at com.ibm.dcm.taskNxslt.execute(taskNxslt.java:117) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106) at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155) at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293) at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106) at org.apache.tools.ant.Task.perform(Task.java:348) at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68) at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293) at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106) at org.apache.tools.ant.Task.perform(Task.java:348) at org.apache.tools.ant.Target.execute(Target.java:435) at org.apache.tools.ant.Target.performTasks(Target.java:456) at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405) at org.apache.tools.ant.Project.executeTarget(Project.java:1376) at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41) at org.apache.tools.ant.Project.executeTargets(Project.java:1260) at org.apache.tools.ant.Main.runBuild(Main.java:853) at org.apache.tools.ant.Main.startAnt(Main.java:235) at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285) at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112) Caused by: java.lang.ClassNotFoundException: org.apache.xalan.processor.TransformerFactoryImpl at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1388) at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1337) at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1089) at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ... 30 more   Total time: 0 seconds com.urbancode.air.ExitCodeException: Command failed with exit code: 1

I noticed that in XSLCache.Java we do the following 

 private XSLCache (Project project) {
    xformFactory = new org.apache.xalan.processor.TransformerFactoryImpl();;
    antProject = project;
  }

But we do not import the class but import the super class "javax.xml.transform.TransformerFactory". 

In order to resolve the issue, do we need to import the xalan.jar file ?

Here is the link for the plugin - https://developer.ibm.com/urbancode/plugin/websphere-datapower-configuration-manager/

Original Question: https://developer.ibm.com/answers/questions/240186/ucd-datapower-plugin-step-execution-failed/?smartspace=urbancode

**Comment by moraesf** [comment]
What Java version is being used? The issue should not occur if the IBM Java is used.

**Comment by jjmgibm** [comment]
I've had the same problem -- I talked to Rich Groot about it a good year ago.  And I was using IBM Java.  I forget how I got around it, but it is definitely a real problem.

**Comment by abhip** [comment]
I can ask the customer what version of Java they are using. However when we imported the  xalan.jar file it worked. 

Would you update the documentation stating that if IBM java not used then this issue may occur ? (Is this a valid statement ?

**Comment by richgroot** [comment]
I've been working on this issue but haven't quite doped out the correct
solution yet.  The issue is that xalan is present in the plugin but it
isn't being referenced at run time.  I'd like to get this resolved this
week but we'll see.

**Comment by cyber-r** [comment]
Any update on this issue ? 

How do i get previous stable version of this plugin i.e '6'. Anyone ?

**Comment by richgroot** [comment]
The two most recent commits correct this problem both for the UCD DP plugin and for the command-line jar file.

**Comment by aouyang2415** [comment]
Did I miss anything? I don't see a solution in this tread.
