### ISSUE TITLE
Import Object DCM Target

### ISSUE THREAD

**Issue by bmarur** [ibm-datapower/datapower-configuration-manager#61]
Hello Experts,

I'm looking at the DCM ANT Targets to import deployment policy object (zip) in to a particular domain and export all objects from that domain , I was wondering, If you could please point me to the ANT targets that are capable to do a simple import object and export all objects and all files of a given domain.  

Thanks,
Bharath

**Comment by nhmathis** [comment]
Hi,

All Ant targets are available in the [deploy.ant.xml](https://github.com/ibm-datapower/datapower-configuration-manager/blob/2a2a2b81e455afd1768f5ee6b0464ecd58dd6f6b/deploy.ant.xml) file. Between line 20 and 80 most, if not all, ant targets with a short description are listed. 

Specifically, you want to look at the `import-*` commands to move .zip/artifacts into DataPower and the `export-object` to create an export.zip file. Note, the `export-object` target can export all objects from a target domain.
