### ISSUE TITLE
Export All Objects Error (uDeploy)

### ISSUE THREAD

**Issue by bmarur** [ibm-datapower/datapower-configuration-manager#63]
Hello Experts,

I'm working with uDeploy to automate our deployments and as part of this, I have been trying to export object through "export-object" target. I seem to get an error while executing the Process steps.

`/apps/udeploy/agent_iaseng/var/plugins/com.ibm.datapower_14_c3a2c3a968584fd4f581528bd2cd099e0dfe97663c61ee533cccf732af1b63f6/dcm/deploy.ant.xml:658: The following error occurred while executing this line:
/apps/udeploy/agent_iaseng/var/plugins/com.ibm.datapower_14_c3a2c3a968584fd4f581528bd2cd099e0dfe97663c61ee533cccf732af1b63f6/dcm/src/dcm-taskdefs.ant.xml:138: Failed to export object all-objects of class=all-classes from domain Test_Bharath on nc-wec-esbgw-a0r.wellsfargo.com.`

I have tried to change the export.file property just to see If that is actually the culprit while running the process steps, I didn't get beyond this error. 

I have attached the logs for your reference, Could you Please take a look at it and let me know If there is something wrong with my process step.

[Export_Object_uDeploy_Error.txt](https://github.com/ibm-datapower/datapower-configuration-manager/files/1137738/Export_Object_uDeploy_Error.txt)

Thanks,
Bharath

**Comment by nhmathis** [comment]
Hi,

The supplied class and object names appear to be invalid. I see you are specifying `all-classes` and `all-objects`. Have you tried specifying a `*`, `**`, or `**.*` instead? I do not believe the `all-*` will be resolved as you expect.

Have you been able to successfully export a single object?

There is an [`export-objects` DCM task](https://github.com/dorser/datapower-configuration-manager/blob/69a83b39c5172abbe61776e2a2e0f61937c7c26f/deploy.ant.xml#L666). This is likely what you are looking for. However, it is not implemented as a plugin step. 

-Nick

**Comment by dorser** [comment]
Hi @bmarur and @nhmathis ,
I suspect this is related to: https://github.com/ibm-datapower/datapower-configuration-manager/pull/60

You are using version 14 which was packaged in June with this bug.
As there is no default value for the all.files property, executing the export-object task will always fail :(

@bmarur  - you can pull the latest version and re-build the plugin and load it into uDeploy or downgrade to an older version.

@nhmathis - Is it possible to update it here: https://developer.ibm.com/urbancode/plugin/websphere-datapower-configuration-manager/ ?


BR,
Dor.

**Comment by bmarur** [comment]
Hi @dorser and @nhmathis 

I was able to execute the object.name="all-objects" and object.class="all-classes" on direct DCM project, PFA logs

[Export_All_Objects_DCM.txt](https://github.com/ibm-datapower/datapower-configuration-manager/files/1145087/Export_All_Objects_DCM.txt)


**command**
ant -f deploy.ant.xml -Ddcm.dir=. -Dhost=nc-wec-esbgw-a0r.company.com -Duid=xgidbrt -Dpwd=xxxxx -Ddomain=Test_Bharath -Dobject.class=all-classes -Dobject.name=all-objects -Dexport.file="C:/Users/u583874/Documents/dcm/ant_tutorials/export/Test_Bharath.zip" -Dcapturesoma="C:/Users/u583874/Documents/dcm/ant_tutorials/capture_soma" -Dall.files=true -v export-object

PFB Export snapshot
![image](https://user-images.githubusercontent.com/28853701/28166293-546b1030-67a5-11e7-9167-6235d8ca9f73.png)

I'm trying to execute the same command over uDeploy and it fails, Please let me know, If you want me to raise a PMR to take this issue to IBM.

Thanks,
Bharath

**Comment by nhmathis** [comment]
[Version 15](https://github.com/ibm-datapower/datapower-configuration-manager/releases/tag/15) has been released which includes this new all.files default property. Closing.
