### ISSUE TITLE
Import-with-def Error

### ISSUE THREAD

**Issue by bmarur** [ibm-datapower/datapower-configuration-manager#64]
Hello Experts,

I'm trying out "Import-with-Def" ANT Target as part of our deployment automation task, I ran in to an issue while executing this command to Import zip file based on the definitions. It looks like the java code is broken somewhere while execution, however, when I check DataPower import configuration, I see the objects are imported successfully, There are few objects down but, that could be be due to file missing in the Crypto Certificate objects. I guess import was successful however, java code seems to break at some point after importing zip file. 

PFA console output

[import_with_def_logs.txt](https://github.com/ibm-datapower/datapower-configuration-manager/files/1146395/import_with_def_logs.txt)

**command**
`ant -f deploy.ant.xml -Ddcm.dir=. -Dhost=nc-wec-esbgw-b0r.company.com -Duid=xgidbrt -Dpwd=xxxxx -Ddomain=Test_Build_DEMO -Dupload.file="C:/Users/user/Documents/dcm/ant_tutorials/definitions/dcm_deployment_policy.xml" -Dimport.changes.file="C:/Users/user/Documents/dcm/ant_tutorials/definitions/dcm_deployment_policy.xml" -Dimport.file="C:/Users/user/Documents/dcm/ant_tutorials/export/A-C3G-CCISServices_export_all_objects.zip"  -Dcapturesoma="C:/Users/user/Documents/dcm/ant_tutorials/capture_soma" -Dall.files=true -v upload-from-def import-from-def`

I have attached the definitions file for your reference.

[dcm_deployment_policy.txt](https://github.com/ibm-datapower/datapower-configuration-manager/files/1146398/dcm_deployment_policy.txt)

Could you please look in to this and let me know where does the command seem to break

Thanks,
Bharath

**Comment by nhmathis** [comment]
You have a small `No access to file`. This is an error that is returned by the SOMA command. Unfortunately, there isn't a simple error code to identify. Fortunately, in v13 I added `Ignore Error` property. Using this property, you can specify the type of error you would like to ignore. 

From what I see, other than that small `No access to file` error which SOMA throws, the import completed successfully.
