### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by samdjones** [ibm-datapower/datapower-configuration-manager#7]
Hello,

Having downloaded the .zip src dist today, I find the build fails because the build appears to attempt to download a file that does not appear to exist (http://www.us.apache.org/dist/ant/binaries/apache-ant-1.9.5-bin.zip). See Ant output below. 

=============

Kochanski:dcm sam$ ant clean distro
Buildfile: /Users/sam/tmp/datapower-configuration-manager-master/dcm/build.xml

clean:

clean:

-get-ant:
    [mkdir] Created dir: /Users/sam/tmp/datapower-configuration-manager-master/dcm/lib
      [get] Getting: http://www.us.apache.org/dist/ant/binaries/apache-ant-1.9.5-bin.zip
      [get] To: /Users/sam/tmp/datapower-configuration-manager-master/dcm/lib/ant.zip
      [get] Error opening connection java.io.FileNotFoundException: http://www.us.apache.org/dist/ant/binaries/apache-ant-1.9.5-bin.zip
      [get] Error opening connection java.io.FileNotFoundException: http://www.us.apache.org/dist/ant/binaries/apache-ant-1.9.5-bin.zip
      [get] Error opening connection java.io.FileNotFoundException: http://www.us.apache.org/dist/ant/binaries/apache-ant-1.9.5-bin.zip
      [get] Can't get http://www.us.apache.org/dist/ant/binaries/apache-ant-1.9.5-bin.zip to /Users/sam/tmp/datapower-configuration-manager-master/dcm/lib/ant.zip

BUILD FAILED
/Users/sam/tmp/datapower-configuration-manager-master/dcm/build.xml:139: Can't get http://www.us.apache.org/dist/ant/binaries/apache-ant-1.9.5-bin.zip to /Users/sam/tmp/datapower-configuration-manager-master/dcm/lib/ant.zip

Total time: 0 seconds

**Comment by samdjones** [comment]
NB: this is my environment:

Kochanski:dcm sam$ ant -v
Apache Ant(TM) version 1.9.6 compiled on June 29 2015
Trying the default build file: build.xml
Buildfile: /Users/sam/tmp/datapower-configuration-manager-master/dcm/build.xml
Detected Java version: 1.8 in: /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre
Detected OS: Mac OS X
parsing buildfile /Users/sam/tmp/datapower-configuration-manager-master/dcm/build.xml with URI = file:/Users/sam/tmp/datapower-configuration-manager-master/dcm/build.xml
Project base dir set to: /Users/sam/tmp/datapower-configuration-manager-master/dcm
parsing buildfile jar:file:/usr/local/Cellar/ant/1.9.6/libexec/lib/ant.jar!/org/apache/tools/ant/antlib.xml with URI = jar:file:/usr/local/Cellar/ant/1.9.6/libexec/lib/ant.jar!/org/apache/tools/ant/antlib.xml from a zip file

**Comment by richgroot** [comment]
Yes, please change the 1.9.5 to 1.9.6 and you'll get around that problem.

I need to find a way to simply get the latest version without embedding a
particular version number.

**Comment by samdjones** [comment]
OK thanks, however I'm not sure assuming the latest version will work is such a good idea - there might be regression issues so I would tie this version of DCM to a particular version of Ant.

The correct solution to use Apache Ivy to manage such dependencies in a more robust manner (no hard-coding URL's to libs that are moved/deleted by their owners). That's a borderline enhancement however.

Workaround is sufficient however -> [Close]
