### ISSUE TITLE
PasswordAlias object not getting created

### ISSUE THREAD

**Issue by sekhardutta** [ibm-datapower/datapower-configuration-manager#73]
Hi Team
With the current code PasswordAlias object is not getting created in DataPower. I just modified code in  SOMA.java class and recreated jar in my local and then it is started working. The new code is as below. Please include it in next release.  

/**
   * This method implements the AddPasswordMap operation.
   * 
   * The params must contain:
   * 
   * domain= ... some domain name ... 
   * aliasname= ... passwordAlias object name to show to the world ... 
   * type= ... real, secret password ... Not needed anymore
   * password= ... actual password ...
   * The params may contain:
   * 
   * ignore-errors=on or off
   * 
   * @param params
   * @return NamedParams "rawresponse".
   * @throws Exception
   */
  public NamedParams doAddPasswordMap (NamedParams params) throws Exception {
    params.insistOn (new String[] {"domain", "aliasname", "password"});

    // Make the request of the XML Management Interface.
    StringBuffer body = new StringBuffer ();
    body.append("<AddPasswordMap>");
    body.append("<AliasName>" + params.get("aliasname") + "</AliasName>");
    body.append("<Password>" + params.get("password") + "</Password>");
    body.append("</AddPasswordMap>");

    String request = SomaUtils.getDoActionEnvelope (params.get("domain"), body.toString());
    NamedParams result = params;
    if (errorsAreSignificant(params)) {
      result = conn.sendAndReceive (params, request);
      insistSomaResultIsOkay(result);
    } else {
      // Do the operation, ignoring the response and any exceptions.
      try {
        result = conn.sendAndReceive (params, request);
      } catch (Exception e) {
      }
    }

    return result;
  }

**Comment by nhmathis** [comment]
Hi,

Could you please create a pull request with this new code? 

Thanks!

**Comment by nhmathis** [comment]
New PR #75
All questions and comments should be resolved there.
