### ISSUE TITLE
stylesheet parameters?

### ISSUE THREAD

**Issue by samdjones** [ibm-datapower/datapower-configuration-manager#8]
There doesn't seem to be an obvious solution for adding/deleting/modifying individual stylesheet parameters attached to specific objects.

Is there a way to use DCM for such tasks?

**Comment by richgroot** [comment]
Can you give me an example to work with?  (If I understand what you mean
then yes, it can be done.)

**Comment by samdjones** [comment]
See below - we would want the DCM task to replace value-1 and value-2 based on properties keyed by param-1 and param-2

```xml

<StylePolicyAction name="foo_rule_0_xform_0"
<!-- etc.. -->
	<StylesheetParameters>
		<ParameterName>param-1</ParameterName>
		<ParameterValue>value-1</ParameterValue>
	</StylesheetParameters>
	<StylesheetParameters>
		<ParameterName>param-2</ParameterName>
		<ParameterValue>value-2</ParameterValue>
	</StylesheetParameters>
<!-- etc.. -->
</StylePolicyAction>

**Comment by samdjones** [comment]
I managed to work it out anyway - please see objects-from-def input below. Merry xmas :-)

This may not be the most concise solution however..?

```xml
<dcm:definition xmlns:dcm="urn:datapower:configuration:manager">
	<dcm:object-modify class="StylePolicyAction" name="foo_rule_0_xform_0">
		<dcm:vector-replace class="StylesheetParameters" ParameterName="param-1">
			<StylesheetParameters>
				<ParameterName>param-1</ParameterName>
				<ParameterValue>NEW_VALUE</ParameterValue>
			</StylesheetParameters>
		</dcm:vector-replace>
	</dcm:object-modify>
</dcm:definition>

**Comment by richgroot** [comment]
Perfect!  Full marks for working out this inobvious technique!  This is
exactly what I wrote the vector operations to do.
