### ISSUE TITLE
Export config as XML

### ISSUE THREAD

**Issue by zfivgas** [ibm-datapower/datapower-configuration-manager#81]
I don't see the ability to specify the format for XML in the export-object target.  It looks like it is SOMA.java has it in there but the deploy.ant.xml doesn't have the format as a property.  I tried to add it anyway but it still defaulted to .zip.

**Comment by nhmathis** [comment]
I've added a `format` argument to both the `export-object` and `export-objects`, but am unable to confirm its validity. Use this argument to specify either XML or ZIP. ZIP is the default. Feel free to give it a try.

Branch: https://github.com/ibm-datapower/datapower-configuration-manager/tree/format-export-object(s)
Commit: https://github.com/ibm-datapower/datapower-configuration-manager/commit/d01bb2cd4b5440b740dc85ded36a328f0bcbf969

**Comment by zfivgas** [comment]
That looks like it did the trick.  I am now able to export the configurations as XML.  Thank you.

**Comment by nhmathis** [comment]
Merged
