### ISSUE TITLE
import-from-def not honoring port property

### ISSUE THREAD

**Issue by bjimba** [ibm-datapower/datapower-configuration-manager#82]
I have a DataPower instance with a non-standard SOMA port configured (10550 instead of 5550), so I set the port in the properties file that I supply to ant.

I can run most tasks fine (check-access, domain-reset, upload-dir), but running 'import-from-def' fails, and I finally narrowed it down to the fact that it ignores the port property and sends the SOMA request to 5550.

**Comment by nhmathis** [comment]
Can you please post some code and logs of what you are seeing? Thanks!

**Comment by nhmathis** [comment]
I believe this change will resolve your issue: 

Branch: https://github.com/ibm-datapower/datapower-configuration-manager/tree/missing-port
Commit: https://github.com/ibm-datapower/datapower-configuration-manager/commit/c75f74a97d22679ad4990a90a6a9d8ef1c23838c

**Comment by bjimba** [comment]
Confirmed.  I built DCM from 'missing-port' branch, and now both the 'import-from-def' and 'import-dpo' are correctly using the non-standard port.  Well done!

**Comment by nhmathis** [comment]
Merged
