### ISSUE TITLE
Export a single service

### ISSUE THREAD

**Issue by iqsougata** [ibm-datapower/datapower-configuration-manager#89]
We are trying to automate DataPower automation using ANT and DCM. The requirement is to export a single service. The following command is being used

ant -f deploy.ant.xml -Ddcm.dir=. -Dhost=xxxxxx -Duid=xxxxxx -Dpwd=xxxxx -Ddomain=default -Dobject.class=MultiProtocolGateway -Dobject.name=ucdDemo -Dexport.file="./exports" -v export-object

The response received is 
export-object:
Property "format" has not been set
Property "format" has not been set
Property "export_success" has not been set
Property "export_response" has not been set
     [echo] Raw response for export: ${export_response}

Any help would be appreciated.

#

**Comment by nhmathis** [comment]
The `format` error you are seeing has been resolved in release v18. Have you updated to the latest version? What version are you using here?

**Comment by iqsougata** [comment]
I have downloaded the source from github and built it. I am using the same with my ANT scripts. Is there any command to check the version ?

**Comment by nhmathis** [comment]
There are compiled `dcm.jar` files in the Releases tab. I suggest you try v19 of the `dcm.jar`. 

If your code is older than 3 weeks old, than you likely don't have the updated jar.

**Comment by iqsougata** [comment]
Used the latest jar. Have the same error. 
Do you want to download the complete new code and try again ?

**Comment by nhmathis** [comment]
Yes, please. You will also need the latest version of `deploy.ant.xml` .

**Comment by iqsougata** [comment]
Thanks a lot. The issue has been fixed
