### ISSUE TITLE
Not Possible to Pass multiple properties

### ISSUE THREAD

**Issue by datentod** [ibm-datapower/datapower-configuration-manager#9]
When using as UrbanCode plugin, its not possible to pass multiple property values.

For example from command line it would like this:

ant -f deploy.ant.xml -Ddcm.dir=. -Dhost=*masked* -Ddomain=BLAH -Duid=admin -Dpwd=*masked* -Dservice.name=LondonTrades -Dservice.type="MultiProtocolGateway" service-status

Same thing through a UrbanCode gui, there you add "Invoke any deploy.ant.xml target". In the add. prop. field I would put service.name=LondonTrades service.type=MultiProtocolGateway and it would never work. I tried separating by comma,etc putting them in quotes, dosent work. The only thing that works if a single property value is stated(e.g. only service.name OR service.type but not BOTH)

From your code(plugin.xml):
      <property name="addlProperties">
        <property-ui type="textBox" default-value="" label="Additional Properties" description="Additional property mappings - antpropname=...[ '~' more definitions ]" hidden="true"/>
      </property>

**Comment by datentod** [comment]
Never mind, it works, found separator.

**Comment by jjmgibm** [comment]
@datentod - what was the separator you used?

**Comment by richgroot** [comment]
Tilde:

a=b~c=d
