### ISSUE TITLE
Getting authentication error while working with download-files target

### ISSUE THREAD

**Issue by Pavan3537** [ibm-datapower/datapower-configuration-manager#92]
Hello Team,
We have a requirement to download all files from the local directory of the DataPower. 
To meet my requirement I am working with **download-files** target. When I am running this target , we are able to read all files from the Local directory of DataPower and getting authentication error while writing those files in specified directory of the Local machine(Windows).
Please suggest me to how can I  resolve the issue and attaching the snapshot for the reference.
![download-files_error](https://user-images.githubusercontent.com/31321495/37333670-32e66314-26aa-11e8-87a9-f7e8dddd0488.PNG)

**Comment by nhmathis** [comment]
Hi,

In my experience, it's one of two issues:

1) You are specifying invalid username and password credentials. Double check that you can use the pavan username and XXXXX password.

2) The datapower instance may not be ready to for XML connections. I tried to give a quick description of it here: https://developer.ibm.com/urbancode/plugindoc/ibmucd/ibm-datapower-configuration-manager/1-2/usage/

It will require you to ssh into the datapower machine and running two commands. 
```
Enable the XML connection via the DataPower cli...
     - xml-mgmt 0 5550;
     - write mem;
```

**Comment by Pavan3537** [comment]
Hello nhmathis,
Thanks for your support.I have doubt regarding to setp-2.
Step-1: To download artifacts from DataPower I am passing correct crede

**Comment by Pavan3537** [comment]
Hello nhmathis,
Thanks for your support.I have a doubt regarding to setp-2.
Step-1: To download artifacts from DataPower I am passing valid credentials only.it will be clear.
Step-2:
I am executing download-files target through command line and I gone through link provided by you,it is implemented using docker-datapower instance using UCD agent.
You want to me work with UCD agent to download file -store from DataPower.
Is there any way to work with command line to execute the download-files target.
Could you please give a bit clarity on that.

Thanks in Advance...!

**Comment by nhmathis** [comment]
If you can't write files to the local machine, your agent...
1) May not be running with the correct permissions. Restart the agent using the `root` user. 
or
2) The folder does not have write permissions. Simple `chmod 777 folder` may temporary get around this issue.  

The suggest identifying the correct agent runtime user that will have the permissions to create your files.

**Comment by richgroot** [comment]
I believe that the downloadFiles task in dcm-taskdefs.ant.xml expects XML
in this form:

<downloadFiles>
    <file>urlopen.xsl</file>
</downloadFiles>

Hope that helps.



On Wed, Apr 4, 2018 at 3:21 AM, Pavan Kumar Meduri <notifications@github.com

**Comment by Pavan3537** [comment]
Hello **richgroot**

Thanks for the quick response,we need to pass **file name** as a property to run the target. How can we pass property value in this form:
<downloadFiles>
    <file>urlopen.xsl</file>
</downloadFiles>

Could you please elaborate it briefly .

**Comment by Pavan3537** [comment]
Hello **richgroot**,
Thank you for your support,It is working
**-Dfiles="<downloadFiles><file>/urlopen.xsl</file></downloadFiles>"**

**Comment by Pavan3537** [comment]
Thanks for supprot @nhmathis @richgroot
