### ISSUE TITLE
This file doesn't contain a dcm:definition element

### ISSUE THREAD

**Issue by letakeda** [ibm-datapower/datapower-configuration-manager#95]
I´m trying to upload a file and I´m running this:
> ant -f EDP.ant.xml -Ddevice=erm02 -Denvironment=scvdev -Dupload.file=../XSLTs/RoutingDEV_20181031_modified.xsl -DremoteDir=local:///XSLT upload-from-def

Buildfile: /Users/leandrotakeda/OneDrive/DataPower/Exports/EDP.ant.xml
     [echo] Loaded device properties from /Users/leandrotakeda/OneDrive/DataPower/Exports/device.erm02.properties.
     [echo] Loaded environment properties from /Users/leandrotakeda/OneDrive/DataPower/Exports/env.scvdev.properties
   [delete] Deleting directory /Users/leandrotakeda/OneDrive/DataPower/Exports/tmp
    [mkdir] Created dir: /Users/leandrotakeda/OneDrive/DataPower/Exports/tmp

clean:
   [delete] Deleting directory /Users/leandrotakeda/OneDrive/DataPower/Exports/tmp

-init-dir:
    [mkdir] Created dir: /Users/leandrotakeda/OneDrive/DataPower/Exports/tmp

-check-std-args:

check-access:

upload-from-def:
    [nxslt] nxslt running /Users/leandrotakeda/OneDrive/DataPower/ContinuousIntegration/datapower-configuration-manager-master/src/remove-unwanted-elements.xsl on ../XSLTs/RoutingDEV_20181031_modified.xsl producing tmp
    [nxslt] Warning:  The encoding 'UTF-8' is not supported by the Java runtime.
    [nxslt] Warning: encoding "UTF-8" not supported, using UTF-8
    [nxslt] nxslt running /Users/leandrotakeda/OneDrive/DataPower/ContinuousIntegration/datapower-configuration-manager-master/src/upload-to-ant.xsl on tmp producing /Users/leandrotakeda/OneDrive/DataPower/Exports/tmp/upload.ant.xml
    [nxslt] Warning:  The encoding 'UTF-8' is not supported by the Java runtime.
    [nxslt] Warning: encoding "UTF-8" not supported, using UTF-8
    [nxslt] SystemId Unknown; Line #78; Column #28; This file doesn't contain a dcm:definition element!
    [nxslt] SystemId Unknown; Line #80; Column #42; Failed to generate internal template due to errors listed above.
    [nxslt] (Location of error unknown)Stylesheet directed termination

BUILD FAILED
/Users/leandrotakeda/OneDrive/DataPower/ContinuousIntegration/datapower-configuration-manager-master/deploy.ant.xml:1132: The following error occurred while executing this line:
/Users/leandrotakeda/OneDrive/DataPower/Exports/tmp/upload.ant.xml:1: Premature end of file.

Total time: 3 seconds

I´m not sure If I understood the dcm definiton file. What am I missing?

Thanks!

**Comment by letakeda** [comment]
>

**Comment by nhmathis** [comment]
[Duplicate](https://github.com/ibm-datapower/datapower-configuration-manager/issues/96)

[Answer](https://github.com/ibm-datapower/datapower-configuration-manager/issues/96#issuecomment-457935745)
