### ISSUE TITLE
This file doesn't contain a dcm:definition element!

### ISSUE THREAD

**Issue by letakeda** [ibm-datapower/datapower-configuration-manager#96]
I´m trying to upload a file under my DataPowers and I´m seeing the error message below.

`ant -f EDP.ant.xml -Ddevice=erm02 -Denvironment=scvdev -Dupload.file=../XSLTs/RoutingDEV_20181031_modified.xsl -DremoteDir=local:///XSLT upload-from-def`

Buildfile: /Users/leandrotakeda/OneDrive/DataPower/Exports/EDP.ant.xml
     [echo] Loaded device properties from /Users/leandrotakeda/OneDrive/DataPower/Exports/device.erm02.properties.
     [echo] Loaded environment properties from /Users/leandrotakeda/OneDrive/DataPower/Exports/env.scvdev.properties
   [delete] Deleting directory /Users/leandrotakeda/OneDrive/DataPower/Exports/tmp
    [mkdir] Created dir: /Users/leandrotakeda/OneDrive/DataPower/Exports/tmp

clean:
   [delete] Deleting directory /Users/leandrotakeda/OneDrive/DataPower/Exports/tmp

-init-dir:
    [mkdir] Created dir: /Users/leandrotakeda/OneDrive/DataPower/Exports/tmp

-check-std-args:

check-access:

upload-from-def:
    [nxslt] nxslt running /Users/leandrotakeda/OneDrive/DataPower/ContinuousIntegration/datapower-configuration-manager-master/src/remove-unwanted-elements.xsl on ../XSLTs/RoutingDEV_20181031_modified.xsl producing tmp
    [nxslt] Warning:  The encoding 'UTF-8' is not supported by the Java runtime.
    [nxslt] Warning: encoding "UTF-8" not supported, using UTF-8
    [nxslt] nxslt running /Users/leandrotakeda/OneDrive/DataPower/ContinuousIntegration/datapower-configuration-manager-master/src/upload-to-ant.xsl on tmp producing /Users/leandrotakeda/OneDrive/DataPower/Exports/tmp/upload.ant.xml
    [nxslt] Warning:  The encoding 'UTF-8' is not supported by the Java runtime.
    [nxslt] Warning: encoding "UTF-8" not supported, using UTF-8
    [nxslt] SystemId Unknown; Line #78; Column #28; This file doesn't contain a dcm:definition element!
    [nxslt] SystemId Unknown; Line #80; Column #42; Failed to generate internal template due to errors listed above.
    [nxslt] (Location of error unknown)Stylesheet directed termination

BUILD FAILED
/Users/leandrotakeda/OneDrive/DataPower/ContinuousIntegration/datapower-configuration-manager-master/deploy.ant.xml:1132: The following error occurred while executing this line:
/Users/leandrotakeda/OneDrive/DataPower/Exports/tmp/upload.ant.xml:1: Premature end of file.

Total time: 3 seconds

What am I missing here? I´m not sure if I understood the need of a dcm:definition file.

Thanks!

**Comment by nhmathis** [comment]
Hi,

The upload file `../XSLTs/RoutingDEV_20181031_modified.xsl` is malformed. Specifically, this error is referring to a missing <dcm:definition> element. 

Much of the CLI requires the configuration of a "Definitions File". Within the CLI call, it is transforming your .xsl file into the `upload.ant.xml` which it then treats as a definition file. Hence why this error may be a little confusing.

The Datapower CLI's definitions file requires very specific configuration. I've attempted to explain the ins and out of this entire file in the wiki:

- [upload-from-def](https://github.com/ibm-datapower/datapower-configuration-manager/wiki/Ant-targets-for-deploy.ant.xml#upload-from-def)
- [DCM Definitions File]( https://github.com/ibm-datapower/datapower-configuration-manager/wiki/DCM-Definitions-File-Format)
- [Getting Started](https://github.com/ibm-datapower/datapower-configuration-manager/wiki/Quick-Start)

I hope this helps!

**Comment by letakeda** [comment]
Thank you, Nick, I had figured this out but missed to reply here, my bad.
And yes, the wiki explains it correctly but I misunderstood it. I created the file with the correct parameters.

Thanks again!
